version: '3.2'

services:
  api:
    build: image/golang
    ports:
      - ${API_LOCAL_PORT}:80
    tty: true  
    volumes:
      - ./:/app


  pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - ${POSTGRES_LOCAL_PORT}:5432